language: c

os:
  - linux
  - osx

arch:
  - amd64
  - arm64

addons:
  apt:
    packages:
    # packages list: https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
    - gcc-mingw-w64-i686
    - dos2unix
    - libsdl1.2-dev
    - libsdl-image1.2-dev
    - libsdl2-dev
    - libsdl2-image-dev
    - zip

# container-based builds
sudo: false

env:
  - 'SDLVERSION=1'
  - 'SDLVERSION=2'
  - 'CROSS=mingw'

matrix:
  exclude:
    - os: linux
      env: CROSS=mingw
      compiler: clang
    - os: osx
      env: CROSS=mingw
    - os: osx
      arch: arm64
    - os: osx
      compiler: gcc

compiler:
  - gcc
  - clang

before_install:
  - 'if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update > /dev/null ; fi'
  - 'if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$SDLVERSION" = "1" ] ; then brew install sdl sdl_image ; fi'
  - 'if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$SDLVERSION" = "2" ] ; then brew install sdl2 sdl2_image ; fi'
  - 'if [ "$CROSS" = "mingw" ] ; then export CC="i686-w64-mingw32-gcc" ; fi'

script:
  - 'cd $TRAVIS_BUILD_DIR'
  - 'if [ "$CROSS" = "mingw" ] ; then ./configure --prefix-dir=${HOME} --os=MINGW --without-asound --without-oss --without-munt --without-sdl --without-sdl2 --without-pulse ; elif [ "$SDLVERSION" = "1" ] ; then ./configure --prefix-dir=${HOME} --without-sdl2 ; else ./configure --prefix-dir=${HOME} ; fi'
  - 'make -j3'
  - 'make bundle_zip'
  - 'if [ "$TRAVIS_OS_NAME" = "osx" ]; then make bundle_dmg ; fi'
  - 'if [ "$TRAVIS_OS_NAME" = "linux" ] && [ -z "$CROSS" ] ; then make install ; fi'
